apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp-operator-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: webapp-operator-role
  namespace: default
rules:
- apiGroups: ["example.com"]
  resources: ["webapps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "get", "list"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webapp-operator-rb
  namespace: default
subjects:
- kind: ServiceAccount
  name: webapp-operator-sa
  namespace: default
roleRef:
  kind: Role
  name: webapp-operator-role
  apiGroup: rbac.authorization.k8s.io
